FROM python:3.11-slim

RUN apt-get update && apt-get install -y gcc python3-dev git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY test_leds_rpi.py .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]